### ISSUE TITLE
Error!!!! How to Resolve it?

### ISSUE THREAD

**Issue by subaru471171** [luoyily/SoftPal-Tool#2]
C:\Users\arkad\OneDrive\Downloads\Miscalleneous\AmuseCraft>python pal_script_tool.py -d
Traceback (most recent call last):
  File "C:\Users\arkad\OneDrive\Downloads\Miscalleneous\AmuseCraft\pal_script_tool.py", line 348, in <module>
    ds.export_json('script_export.json')
  File "C:\Users\arkad\OneDrive\Downloads\Miscalleneous\AmuseCraft\pal_script_tool.py", line 227, in export_json
    text_obj = self.text_pack.find_text_by_offset(text_offset)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\arkad\OneDrive\Downloads\Miscalleneous\AmuseCraft\pal_script_tool.py", line 140, in find_text_by_offset
    index = self.offset_id_map[offset]
            ~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 20622


I am sendind the files too
[data.zip](https://github.com/user-attachments/files/17992712/data.zip)

**Comment by JiaFeiMiao-K-Cat** [comment]
> C:\Users\arkad\OneDrive\Downloads\Miscalleneous\AmuseCraft>python pal_script_tool.py -d Traceback (most recent call last): File "C:\Users\arkad\OneDrive\Downloads\Miscalleneous\AmuseCraft\pal_script_tool.py", line 348, in ds.export_json('script_export.json') File "C:\Users\arkad\OneDrive\Downloads\Miscalleneous\AmuseCraft\pal_script_tool.py", line 227, in export_json text_obj = self.text_pack.find_text_by_offset(text_offset) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\arkad\OneDrive\Downloads\Miscalleneous\AmuseCraft\pal_script_tool.py", line 140, in find_text_by_offset index = self.offset_id_map[offset] ~~~~~~~~~~~~~~~~~~^^^^^^^^ KeyError: 20622
> 
> I am sendind the files too [data.zip](https://github.com/user-attachments/files/17992712/data.zip)

You can parse the `TEXT.DAT.dec` directly, and I have converted it to a txt with this format:
```
line number
content
line number
content
...
```
The keypoint is deal with line-delimiters(usually `/x00/x00`) and line-numbers(some bytes in a single line)

Here is the code and files:
[SoftPalTool-issue-2.zip](https://github.com/user-attachments/files/23170265/SoftPalTool-issue-2.zip)
